name: Test and Release

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test

  build:
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: setu-linux-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: setu-macos-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: setu-windows-x86_64.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/setu${{ matrix.os == 'windows-latest' && '.exe' || '' }}